blog/urls.py
from django.urls import path
from . import views
from blog.views import SearchArticleView

app_name = 'blog'

urlpatterns = [
    path('', views.list_of_articles, name='list_of_articles'),
    #path('<int:id>/', views.article_details, name='article_details'),
    path('<int:year>/<int:month>/<int:day>/<slug:article>/', views.article_details, name='article_details'),
    path('<int:article_id>/comment/', views.comment_for_article, name='comment_for_article'),
    path('tag/<slug:tag_slug>', views.list_of_articles, name='list_of_articles_by_tag'),
    path('search/', views.article_search, name='article_search'),
     path('search2/', SearchArticleView.as_view(), name='article_search2'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'areticles': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.
class ArticlePublishedManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status=Article.Status.PUBLISHED)


class Article(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_articles')

    objects = models.Manager()
    publishedArticles = ArticlePublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:article_details',
                       args=[
                           self.publish.year,
                           self.publish.month,
                           self.publish.day,
                           self.slug 
                       ])
    

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.article}'
    

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import View
from django.views.decorators.http import require_POST
from django.db.models import Count
from taggit.models import Tag
from .models import Article, Comment
from .forms import CommentForm, SearchForm

# Create your views here.
def list_of_articles(request, tag_slug = None):
    articles = Article.publishedArticles.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        articles = articles.filter(tags__in = [tag])

    paginator = Paginator(articles, 3)
    page_number = request.GET.get('page', 1)

    try:
        articles = paginator.page(page_number)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        articles = paginator.page(1)    

    return render(request, 'blog/list.html', {'articles': articles, 'tag': tag})


def article_details(request, year, month, day, article):
    try:
        article = get_object_or_404(Article, status=Article.Status.PUBLISHED,
                                    slug=article,
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day
                                    )
        
        comments = article.comments.filter(active=True)
        
        form = CommentForm()

        article_tags_ids = article.tags.values_list('id', flat=True)
        similar_published_articles = Article.publishedArticles.filter(tags__in=article_tags_ids)\
                                .exclude(id=article.id)
        similar_articles = similar_published_articles.annotate(same_tags_in_article=Count('tags'))\
                                .order_by('-same_tags_in_article','-publish')[:3]
    except Article.DoesNotExist:
        raise Http404('No article found.')
    
    return render(request, 'blog/detail.html', {
        'article': article,
        'comments': comments,
        'form': form,
        'similar_articles': similar_articles
        })

def article_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Article.objects.raw("SELECT * FROM blog_article WHERE MATCH (title, body) AGAINST (%s)", [query])

    return render(request, 
                  'blog/search.html',
                  { 'form': form, 'query': query, 'results': results }
                  )

@require_POST
def comment_for_article(request, article_id):
    article = get_object_or_404(Article, id = article_id, status = Article.Status.PUBLISHED)
    comment = None

    form = CommentForm(data=request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.article = article
        comment.save()

    return render(request, 'blog/comment.html', {'article': article, 'form': form, 'comment': comment})


class SearchArticleView(View):
    query = None
    results = []
    form_class = SearchForm

    def get(self, request):
        form = self.form_class
        
        if 'query' in request.GET:
            
            form = self.form_class(request.GET)
            if form.is_valid():
                query = form.cleaned_data['query']
                results = Article.objects.raw("SELECT * FROM blog_article WHERE MATCH (title, body) AGAINST (%s)", [query])
                return render(request, 'blog/search.html', {'form': form, 'query': query,'results': results})
                
        return render(request, 'blog/search.html', {'form': form})

blog/templates/blog/base.html
{% load article_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>
<body>
    
    <div class="header">
        <h2>Personal Blog</h2>
    </div>

    <div class="row">
        <div class="leftcolumn">
            <div class="card">
                {% block content %}
                {% endblock %}
            </div>
            
        </div>
        <div class="rightcolumn">
            <div class="card">
                <h2>Blogger Website</h2>
                <p>This is my blogger website.</p>
                <p>I have published {% total_articles %} articles till now.</p>
            </div>
            
            <div class="card">
                <h3>Latest Article</h3>
                {% block latestArticle %}
                    {% show_latest_articles 3 %}
                {% endblock %}
            </div>
            
            <div class="card">
                <h3>Most Commented Article</h3>
                {% block mostCommentedArticle %}
                    {% show_most_commented_articles 3 %}
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="footer">
        <h5>Copyright 2023 All Right Revered </h5>
    </div> 

</body>
</html>

blog/templates/blog/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href={{ article.get_absolute_url }}>Back to the article</a></p>
    {% else %}
        {% include "blog/comment_form.html" %}
    {% endif %}

{% endblock %}

blog/templates/blog/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:comment_for_article" article.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <h1>{{ article.title }}</h1>
    <p>
        Published {{ article.publish }} by {{ article.author }}
    </p>
    {{ article.body|linebreaks }}

    <h2>Similar articles</h2>
        {% for article in similar_articles %}
            <p>
                <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
            </p>
        {% empty %}
            There are no similar articles.
        {% endfor %}
    
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div>
            <p>
                Comment {{ forloop.counter }} by {{ comment.name }} on {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <div>
            <p>There are no comments.</p>
        </div>
    {% endfor %}

    {% include "blog/comment_form.html" %}
    
    <a href="/blog/">
        Go back to the Articles
    </a>

{% endblock %}

blog/templates/blog/latest_articles.html
<ul>
    {% for latest_article in latest_articles %}
        <li>
            <a href="{{ latest_article.get_absolute_url }}">{{ latest_article.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/list.html
{% extends "blog/base.html" %}

{% block title %}Articles{% endblock %}

{% block content %}
    {% if tag %}
        <h2>Articles tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for article in articles %}
        <h2>
            <a href={{ article.get_absolute_url }} >
                {{ article.title }}
            </a>
        </h2>
        <p>
            Tags: 
            {% for tag in article.tags.all %}
                <a href="{% url "blog:list_of_articles_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p>
            Published {{ article.publish }} by {{ article.author }}
        </p>
        {{ article.body|truncatewords:50|linebreaks }}

    {% endfor %}
    {% include "blog/pagination.html" with page=articles %}
{% endblock %}

blog/templates/blog/most_commented_articles.html
<ul>
    {% for most_commented_article in most_commented_articles %}
        <li>
            <a href="{{ most_commented_article.get_absolute_url }}">{{most_commented_article.title}}</a>
        </li>

    {% endfor %}

</ul>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="pagination-links">

        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/search.html
{% extends "blog/base.html" %}
{% load article_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Article containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
    
        {% for article in results %}
            <h4>
            <a href="{{ article.get_absolute_url }}">
                {{ article.title }}
            </a>
            </h4>
            {{ article.body|truncatewords:50 }}
            {% empty %}
            <p>No results found.</p>
        {% endfor %}

        <p><a href="{% url "blog:article_search" %}">Search again</a></p>
        
    {% else %}

        <h1>Search for articles</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>

    {% endif %}
{% endblock %}